from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from sqlalchemy import func

from app.database import get_db
from app.models.user import User
from app.models.quiz import Quiz
from app.models.attempt import Attempt
from app.models.upload import Upload
from app.middleware.auth import get_current_user
from pydantic import BaseModel
from typing import Optional
from datetime import datetime

router = APIRouter(prefix="/api/analytics", tags=["Analytics"])


# ─── Response schemas ────────────────────────────────────────────────────────

class RecentAttempt(BaseModel):
    attempt_id:   int
    quiz_id:      int
    quiz_title:   str
    difficulty:   str
    score:        int
    total:        int
    percentage:   float
    time_taken:   Optional[int]
    attempted_at: datetime

    class Config:
        from_attributes = True


class DashboardStats(BaseModel):
    total_quizzes:    int      # total quizzes generated by user
    total_attempts:   int      # total quiz attempts submitted
    avg_score:        float    # average percentage across all attempts
    total_study_time: int      # total seconds spent taking quizzes
    total_documents:  int      # total uploaded documents
    recent_attempts:  list[RecentAttempt]


# ─── Dashboard endpoint ───────────────────────────────────────────────────────

@router.get("/dashboard", response_model=DashboardStats)
def get_dashboard_stats(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Return aggregated stats for the current user's learning activity:
      - Total quizzes generated
      - Total attempts submitted
      - Average score percentage
      - Total study time in seconds
      - Total documents uploaded
      - Last 5 quiz attempts (with quiz title, score, date)
    """
    uid = current_user.id

    # Total quizzes generated
    total_quizzes = db.query(func.count(Quiz.id)).filter(Quiz.user_id == uid).scalar() or 0

    # Total uploads
    total_documents = db.query(func.count(Upload.id)).filter(Upload.user_id == uid).scalar() or 0

    # Attempt aggregates
    attempt_stats = (
        db.query(
            func.count(Attempt.id).label("total_attempts"),
            func.avg(Attempt.percentage).label("avg_score"),
            func.sum(Attempt.time_taken).label("total_time"),
        )
        .filter(Attempt.user_id == uid)
        .first()
    )

    total_attempts   = attempt_stats.total_attempts or 0
    avg_score        = round(float(attempt_stats.avg_score or 0), 1)
    total_study_time = int(attempt_stats.total_time or 0)

    # Recent 5 attempts joined with quiz title
    recent_rows = (
        db.query(Attempt, Quiz)
        .join(Quiz, Attempt.quiz_id == Quiz.id)
        .filter(Attempt.user_id == uid)
        .order_by(Attempt.attempted_at.desc())
        .limit(5)
        .all()
    )

    recent_attempts = [
        RecentAttempt(
            attempt_id=a.id,
            quiz_id=q.id,
            quiz_title=q.title,
            difficulty=q.difficulty,
            score=a.score,
            total=a.total,
            percentage=a.percentage,
            time_taken=a.time_taken,
            attempted_at=a.attempted_at,
        )
        for a, q in recent_rows
    ]

    return DashboardStats(
        total_quizzes=total_quizzes,
        total_attempts=total_attempts,
        avg_score=avg_score,
        total_study_time=total_study_time,
        total_documents=total_documents,
        recent_attempts=recent_attempts,
    )
